### ISSUE TITLE
You're writing your server in Go?

### ISSUE THREAD

**Issue by kingcodefish** [JavascriptFTW/My-Website#1]
Are you literally writing a server manager, or what? And why write it in Go?

**Comment by MrMagma** [comment]
Please do not open issues simply for discussion. Issues should be created for valid problems with the functionality or features of a project.

I _will_ still answer your questions - tomorrow, but _please_ do keep in mind that issued are _not_ intended for casual conversation. Any further questions should be directed at me via Twitter, Google+, or email.

Thank you.

**Comment by MrMagma** [comment]
To answer your questions:
"You're writing your server in Go?" Yes
"Are you literally writing a server manager, or what?" Not entirely sure what you mean, but I think yes.
"And why write it in Go" Because it sounded fun, I want to learn Go, Go is fun, and because.
